[project]
name = "nsst"
version = "0.1.0"
description = "Python library for a Not So Simple Table dynamodb table design."
dependencies = ["click"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project.scripts]
nsst = "nsst.cli:cli"
